changelog:
  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "🔐 Security"
      labels:
        - security
    - title: "💥 Breaking Changes"
      labels:
        - breaking-change
    - title: "📚 Documentation"
      labels:
        - documentation
    - title: "⚙️ Maintenance"
      labels:
        - dependencies
        - chore
  exclude:
    labels:
      - skip-changelog
